---
apiVersion: v2
name: crossplane
description: Umbrella Chart for Crossplane
type: application
version: 0.1.0
dependencies:
  # https://docs.crossplane.io/latest/get-started/install/
  - name: crossplane
    repository: https://charts.crossplane.io/stable
    version: 2.4.0
