apiVersion: v2
name: litmus
description: Umbrella chart for LitmusChaos
type: application
version: 1.0.0
dependencies:
  - name: litmus
    repository: https://litmuschaos.github.io/litmus-helm/
    version: 3.30.0
