apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  labels:
    argocd.argoproj.io/instance: {{ .cluster.name }}-external-secrets
  name: "{{ .cluster.name }}-{{ .cluster.stage }}"
spec:
  provider:
    vault:
      auth:
        userPass:
          path: userpass
          secretRef:
            key: password
            name: stackit-secrets-manager-cred
            namespace: external-secrets
          username: smht0bdgf31sllk4
      path: "85d1e7e5-cc22-4065-ac54-47ebe0520919"
      server: "https://prod.sm.eu01.stackit.cloud"
      version: v2


smht0bdgf31sllk4


1@8p2oZV0B#503,51R


 kubectl -n external-secrets create secret generic stackit-secrets-manager-cred --from-literal=username="smht0bdgf31sllk4" --from-literal=password="1@8p2oZV0B#503,51R"