apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  labels:
    argocd.argoproj.io/instance: {{ .cluster.name }}-external-secrets
  name: "{{ .cluster.name }}-{{ .cluster.stage }}"
spec:
  provider:
    vault:
      auth:
        userPass:
          path: userpass
          secretRef:
            key: password
            name: stackit-secrets-manager-cred
            namespace: external-secrets
          username: sm48f5o7f40e5ytq
      path: "65e91412-973b-4cbb-bfc0-6c1079f386ba"
      server: "https://prod.sm.eu01.stackit.cloud"
      version: v2