version: v1alpha4
clusters:
  - name: hub
    stage: dev
    type: hub
    dnsName: hub-dev.stackit.run
    ssoOrg: la-demos
    ssoTeam: g-gitops
    ingressClassName: traefik
    terraform:
      provider: stackit
      projectId: 38867e9e-b5d4-4a85-97a8-0a944ab75b19
      kubernetesType: ske
      kubernetesVersion: "1.35"
      dns:
        name: hub-dev.stackit.run
        email: artem.lajko@iits-consulting.de
    argocd:
      selfManaged: enabled
      repo:
        https:
          configs:
            url: https://github.com/la-cc/kubara-remote-university.git
            targetRevision: main
          components:
            url: https://github.com/la-cc/kubara-remote-university.git
            targetRevision: main
    catalogs:
      - oci://ghcr.io/kubara-io/catalogs/general:4.0.0
    services:
      cert-manager:
        status: enabled
        config:
          clusterIssuer:
            email: artem.lajko@iits-consulting.de
            name: letsencrypt-prod
            server: https://acme-v02.api.letsencrypt.org/directory
      external-dns:
        status: enabled
      external-secrets:
        status: enabled
      homer-dashboard:
        status: enabled
      kro:
        status: disabled
      kube-prometheus-stack:
        status: enabled
      kyverno:
        status: enabled
      kyverno-policies:
        status: enabled
      kyverno-policy-reporter:
        status: enabled
      loki:
        status: enabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: disabled
      oauth2-proxy:
        status: enabled
      reloader:
        status: disabled
      traefik:
        status: enabled
      vcluster-platform:
        status: disabled
      chaos-mesh:
        status: enabled
      chaoskube:
        status: disabled
      litmus:
        status: disabled
      velero:
        status: disabled
        config:
          backupMode: fs-backup
          backupStorage:
            create: true
            region: eu01
  - name: spoke-1
    stage: dev
    type: spoke
    dnsName: spoke-1.hub-dev.stackit.run
    ingressClassName: traefik
    argocd:
      selfManaged: enabled
      repo:
        https:
          configs:
            url: https://git.example.com/platform/repo.git
            targetRevision: main
          components:
            url: https://git.example.com/platform/repo.git
            targetRevision: main
    catalogs:
      - my-catalog
    services:
      kro:
        status: enabled
  - name: spoke-2
    stage: qa
    type: spoke
    dnsName: spoke-2.hub-dev.stackit.run
    ingressClassName: traefik
    argocd:
      selfManaged: enabled
      repo:
        https:
          configs:
            url: https://git.example.com/platform/repo.git
            targetRevision: main
          components:
            url: https://git.example.com/platform/repo.git
            targetRevision: main
    catalogs:
      - my-catalog
    services:
      kro:
        status: enabled
  - name: spoke-3
    stage: prod
    type: spoke
    dnsName: spoke-3.hub-dev.stackit.run
    ingressClassName: traefik
    argocd:
      selfManaged: enabled
      repo:
        https:
          configs:
            url: https://git.example.com/platform/repo.git
            targetRevision: main
          components:
            url: https://git.example.com/platform/repo.git
            targetRevision: main
    catalogs:
      - my-catalog
    services:
      kro:
        status: enabled
