kamaji:
  enabled: false

tenantControlPlane:
  enabled: true
  name: kamaji-ci
  ingress:
    enabled: true
    hostname: kamaji-ci.example.com:443

ingressRouteTCP:
  enabled: true
  host: kamaji-ci.example.com
