{{- if and .Values.itGrundschutz.standard.enabled (dig "itGrundschutz" "standard" "createDefaultNetworkPolicyNewNamespaces" "enabled" true (merge .Values)) }}
apiVersion: policies.kyverno.io/v1alpha1
kind: GeneratingPolicy
metadata:
  name: create-default-network-policy-new-namespaces
  annotations:
    policies.kyverno.io/title: Create default-deny network policy for new namespaces
    policies.kyverno.io/category: IT-Grundschutz (standard)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: "1.17.0"
    kyverno.io/kyverno-version: {{ .Values.global.kyvernoVersion | quote }}
    kyverno.io/kubernetes-version: {{ .Values.global.k8sVersion | quote }}
    policies.kyverno.io/subject: Namespace, NetworkPolicy
    policies.kyverno.io/description: >-
      By default, Kubernetes allows communications across all Pods within a cluster.
      The NetworkPolicy resource and a CNI plug-in that supports NetworkPolicy must be used to restrict
      communications. A default NetworkPolicy should be configured for each Namespace to
      default deny all ingress and egress traffic to the Pods in the Namespace. This policy
      creates a new NetworkPolicy resource named `default-deny` when a new Namespace is created.
spec:
  evaluation:
    synchronize:
      enabled: true
    admission:
      enabled: true
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - namespaces
  variables:
    - name: targetNs
      expression: "object.metadata.name"
    - name: downstream
      expression: >-
        [
          {
            "kind": dyn("NetworkPolicy"),
            "apiVersion": dyn("networking.k8s.io/v1"),
            "metadata": dyn({
              "name": dyn("default-deny"),
              "labels": dyn({
                "created-by": dyn("kyverno")
              })
            }),
            "spec": dyn({
              "podSelector": dyn({}),
              "policyTypes": dyn(["Ingress", "Egress"])
            })
          }
        ]
  generate:
    - expression: generator.Apply(variables.targetNs, variables.downstream)
{{- end }}
