{{- if and .Values.itGrundschutz.standard.enabled (dig "itGrundschutz" "standard" "disallowPrivilegeEscalation" "enabled" true (merge .Values)) }}
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: disallow-privilege-escalation-itgrundschutz
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: IT-Grundschutz (standard)
    policies.kyverno.io/severity: {{ dig "itGrundschutz" "standard" "disallowPrivilegeEscalation" "severity" "medium" (merge .Values) }}
    policies.kyverno.io/minversion: "1.17.0"
    kyverno.io/kyverno-version: {{ .Values.global.kyvernoVersion | quote }}
    kyverno.io/kubernetes-version: {{ .Values.global.k8sVersion | quote }}
    policies.kyverno.io/subject: Pod, Deployment, StatefulSet, DaemonSet
    policies.kyverno.io/description: >-
      Privilege escalation, such as via set-user-ID or set-group-ID file mode, should not be allowed.
      This policy ensures the `allowPrivilegeEscalation` field is set to `false`.
      This Policy ensures IT-Grundschutz-Rules: SYS.1.6.A17
spec:
  failurePolicy: {{ dig "itGrundschutz" "standard" "disallowPrivilegeEscalation" "webhookFailurePolicy" "Fail" (merge .Values) }}
  webhookConfiguration:
    timeoutSeconds: 30
  evaluation:
    background:
      enabled: {{ dig "itGrundschutz" "standard" "disallowPrivilegeEscalation" "enableBackgroundScanning" true (merge .Values) }}
  validationActions:
    - {{ $action := dig "itGrundschutz" "standard" "disallowPrivilegeEscalation" "actionOverride" (dig "itGrundschutz" "mode" "Audit" (merge .Values)) (merge .Values) }}{{ if eq $action "Enforce" }}Deny{{ else }}{{ $action }}{{ end }}
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
          - apps
          - batch
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - daemonsets
          - deployments
          - jobs
          - statefulsets
          - cronjobs
  variables:
    - name: podSpec
      expression: >-
        object.kind == 'Pod' ? object.spec :
        object.kind == 'CronJob' ? object.spec.jobTemplate.spec.template.spec :
        object.spec.template.spec
    - name: containers
      expression: >-
        variables.podSpec.?containers.orValue([])
        + variables.podSpec.?initContainers.orValue([])
        + variables.podSpec.?ephemeralContainers.orValue([])
  validations:
    - expression: >-
        variables.containers.all(c,
          has(c.securityContext) && c.securityContext.?allowPrivilegeEscalation.orValue(true) == false
        )
      message: >-
        Privilege escalation is disallowed. The fields securityContext.allowPrivilegeEscalation must be set to `false`.
{{- end }}
