{{- if and .Values.bestPractices.enabled (dig "bestPractices" "requirePodDisruptionBudget" "enabled" true (merge .Values)) }}
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: require-pod-disruption-budget
  annotations:
    policies.kyverno.io/title: Require PodDisruptionBudget
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: "1.17.0"
    kyverno.io/kyverno-version: {{ .Values.global.kyvernoVersion | quote }}
    kyverno.io/kubernetes-version: {{ .Values.global.k8sVersion | quote }}
    policies.kyverno.io/subject: Deployment, StatefulSet, PodDisruptionBudget
    policies.kyverno.io/description: >-
      PodDisruptionBudget resources are useful to ensuring minimum availability
      is maintained at all times. This policy checks all incoming Deployments and StatefulSets
      with replicas >= 3 to ensure they have a matching, preexisting PodDisruptionBudget.
spec:
  failurePolicy: {{ dig "bestPractices" "requirePodDisruptionBudget" "webhookFailurePolicy" "Fail" (merge .Values) }}
  webhookConfiguration:
    timeoutSeconds: 30
  evaluation:
    background:
      enabled: {{ dig "bestPractices" "requirePodDisruptionBudget" "enableBackgroundScanning" true (merge .Values) }}
  validationActions:
    - {{ $action := dig "bestPractices" "requirePodDisruptionBudget" "actionOverride" (dig "bestPractices" "mode" "Audit" (merge .Values)) (merge .Values) }}{{ if eq $action "Enforce" }}Deny{{ else }}{{ $action }}{{ end }}
  matchConstraints:
    resourceRules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - deployments
          - statefulsets
  matchConditions:
    - name: check-replicas-min-3
      expression: "object.spec.?replicas.orValue(1) >= 3"
  variables:
    - name: pdbList
      expression: "resource.List('policy/v1', 'poddisruptionbudgets', object.metadata.namespace).items.orValue([])"
  validations:
    - expression: >-
        size(variables.pdbList) > 0 &&
        variables.pdbList.exists(pdb,
          has(pdb.spec) &&
          has(pdb.spec.selector) &&
          has(pdb.spec.selector.matchLabels) &&
          has(object.spec.template.metadata) &&
          has(object.spec.template.metadata.labels) &&
          pdb.spec.selector.matchLabels.all(k, k in object.spec.template.metadata.labels && pdb.spec.selector.matchLabels[k] == object.spec.template.metadata.labels[k])
        )
      message: "There is no corresponding PodDisruptionBudget found for this Deployment/StatefulSet."
{{- end }}
