cluster-api-operator:
  # Argo CD uses the sync-wave annotations emitted by the operator chart.
  enableHelmHook: false

  core:
    cluster-api:
      namespace: capi-system
      version: v1.13.2
      manager:
        featureGates:
          ClusterTopology: true

  bootstrap:
    kubeadm:
      namespace: capi-kubeadm-bootstrap-system
      version: v1.13.2
      manager:
        featureGates:
          ClusterTopology: true

  controlPlane:
    kubeadm:
      namespace: capi-kubeadm-control-plane-system
      version: v1.13.2
      manager:
        featureGates:
          ClusterTopology: true

  infrastructure:
    stackit:
      namespace: cluster-api-provider-stackit-system
      version: v0.1.0-alpha.2
      fetchConfig:
        url: https://github.com/stackitcloud/cluster-api-provider-stackit/releases

namespace:
  labels: {}
  annotations: {}
