bootstrapValues:
  applications:
    - destination:
        serverName: artem
      info:
        - name: type
          value: app-of-apps
      name: app-of-apps
      namespace: argocd
      projectName: artem-dev
      repoUrl: https://github.com/la-cc/kubara-remote-university.git
      repoPath: apps
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /status
            - /metadata/resourceVersion
            - /metadata/generation
            - /metadata/managedFields
            - /spec/ignoreDifferences
