apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kamaji-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kamaji-2
    server: "https://kubernetes.default.svc"
  project: hub-dev
  sources:
    - repoURL: https://github.com/la-cc/kubara-remote-university.git
      targetRevision: main
      path: platform-components/helm/kamaji
      helm:
        ignoreMissingValueFiles: true
        releaseName: "kamaji-2"
        valueFiles:
          - values.yaml
        values: |
          kamaji:
            enabled: false

          tenantControlPlane:
            enabled: true
            name: kamaji-2
            ingress:
              enabled: true
              hostname: kamaji-2.hub-dev.stackit.run:443
            networkProfile:
              certSANs:
                - kamaji-2.hub-dev.stackit.run

          ingressRouteTCP:
            enabled: true
            host: kamaji-2.hub-dev.stackit.run
            annotations:
              external-dns.alpha.kubernetes.io/target: hub-dev.stackit.run
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - FailOnSharedResource=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
