apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vcluster-1
    server: "https://kubernetes.default.svc"
  project: artem-dev
  sources:
    - repoURL: https://github.com/la-cc/kubara-remote.git
      targetRevision: main
      path: platform-components/helm/vcluster
      helm:
        ignoreMissingValueFiles: true
        releaseName: "vcluster-1"
        valueFiles:
          - values.yaml
        values: |
          vcluster:
            controlPlane:
              proxy:
                extraSANs:
                  - vcluster-1.artem-dev.stackit.run
              ingress:
                enabled: false

          ingressRouteTCP:
            enabled: true
            host: vcluster-1.artem-dev.stackit.run
            annotations:
              external-dns.alpha.kubernetes.io/target: artem-dev.stackit.run
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: vcluster-1
      namespace: vcluster-1
      jsonPointers:
        - /spec/updateStrategy
        - /spec/volumeClaimTemplates
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
