{{- if and .Values.argoCD.enabled (dig "argoCD" "preventDefaultProject" "enabled" true (merge .Values)) }}
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: application-prevent-default-project
  annotations:
    policies.kyverno.io/title: Prevent Use of Default Project
    policies.kyverno.io/category: ArgoCD
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: "1.17.0"
    kyverno.io/kyverno-version: {{ .Values.global.kyvernoVersion | quote }}
    kyverno.io/kubernetes-version: {{ .Values.global.k8sVersion | quote }}
    policies.kyverno.io/subject: Application
    policies.kyverno.io/description: >-
      This policy prevents the use of the default project in an Application.
spec:
  failurePolicy: {{ dig "argoCD" "preventDefaultProject" "webhookFailurePolicy" "Fail" (merge .Values) }}
  webhookConfiguration:
    timeoutSeconds: 30
  evaluation:
    background:
      enabled: {{ dig "argoCD" "preventDefaultProject" "enableBackgroundScanning" true (merge .Values) }}
  validationActions:
    - {{ $action := dig "argoCD" "preventDefaultProject" "actionOverride" (dig "argoCD" "mode" "Audit" (merge .Values)) (merge .Values) }}{{ if eq $action "Enforce" }}Deny{{ else }}{{ $action }}{{ end }}
  matchConstraints:
    resourceRules:
      - apiGroups:
          - argoproj.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - applications
  validations:
    - expression: "object.spec.?project.orValue('') != 'default'"
      message: "The default project may not be used in an Application."
{{- end }}
